# Here you can set the paths to the different folders
tmp: "tmp"
results: "results"
worflow: "workflow"
resources: "resources"

# Here you can set the number of threads to use for snakemake
threads: 4

# Here you can change the accessions to download
samples:
  # The tree experiments
  - "SRR10379721"
  - "SRR10379722"
  - "SRR10379723"
  # The three controls
  - "SRR10379724"
  - "SRR10379725"
  - "SRR10379726"
