# Here you can set the paths to the different folders
tmp: "tmp"
results: "results"
workflow: "workflow"
resources: "resources"

# Here you can set the number of threads to use for snakemake
threads: 8

# Here you can see the version of the workflow that is used to run the analysis
# You can either run the "latest" version or the "paper" version
# Uncomment the version you want to use
version: "latest"
# version: "paper"

# Here you can decide whether you want to use the trimming step or not
# If you want to use it, set it to true. If not, set it to false
with_trimming: false

# Here you can change the accessions to download
samples:
  # The tree experiments
  - "SRR10379721"
  - "SRR10379722"
  - "SRR10379723"
  # The three controls
  - "SRR10379724"
  - "SRR10379725"
  - "SRR10379726"

# Here you can change the desired plots
plots:
 - "MA_plot"
#  - "PCA_plot"
#  - "Volcano_plot"

# Here you can change the containers to use
containers:
  base: "docker://juldpnt/reprohackaton_8:alpine"
  sratoolkit: "docker://juldpnt/reprohackaton_8:sratoolkit-3.0.7"
  trimgalore: "docker://mattverlynde/trimgalore:trimgalore-0.6.10-cutadapt-4.2-fastqc-0.11.7"
  # bowtie container differs between latest and paper version
  bowtie: 
    latest: "docker://juldpnt/reprohackaton_8:bowtie-1.2.2"
    paper: "docker://mattverlynde/bowtie:bowtie-0.12.7"
  # subread container differs between latest and paper version
  subread: 
    latest: "docker://juldpnt/reprohackaton_8:subread-2.0.6"
    paper: "docker://juldpnt/reprohackaton_8:subread-1.4.6-p3" 
  Rscript: "docker://juldpnt/reprohackaton_8:deseq2"