---
title: "DeSeq"
output: html_document
---

```{r setup, include=FALSE}
library("DESeq2")

# Création d'un objet DESeqDataSet (dds) avec la matrice et les données de colonnes

subreadCounts <- as.matrix(read.csv("subreadCountsOutput.???",sep="\t",row.names="gene_id"))

subreadData <- read.csv("subreadDataOutput.???", row.names=1)

subreadData <- subreadData[,c("condition","type")]
subreadData$condition <- factor(subreadData$condition)
subreadData$type <- factor(subreadData$type)

dataSet <- DESeqDataSetFromMatrix(countData = subreadCountsOutput, colData = subreadDataOutput, design = ~ condition)

```

```{r}
# analyse d'expression différentielle sur notre dds

dataSet <- DESeq(dataSet)
```

```{r}
# formatage des résultats sous forme de DataFrame

resultats <- results(notresetdedonnees)
```

```{r}
# exportation des résultats sous forme de MA-plot

plotMA(resultats, ylim = "c(limite inférieure du log fold change à afficher, limite supérieure)")
```



plotMA(resultats, ylim = "c(limite inférieure du log fold change à afficher, limite supérieure)")
```

