  ---
  title: "DeSeq"
  output: html_document
  ---

```{r setup, include=FALSE}


# ------------- Preprocess data
subreadCounts <- read.table("counts_nous.txt", header = TRUE, sep = '\t', row.names = 1)
new_colnames <- c("SRR10379721",
                  "SRR10379722",
                  "SRR10379723",
                  "SRR10379724",
                  "SRR10379725",
                  "SRR10379726")

# Change column names by accession number
colnames(subreadCounts)[(ncol(subreadCounts)-5):ncol(subreadCounts)] <- new_colnames

# Remove first 6 columns (chr, start, end, strand, length, name)
subreadCounts <- subreadCounts[,7:ncol(subreadCounts)]

# Convert to matrix
subreadCounts <- as.matrix(subreadCounts)
head(subreadCounts,5)

# Set up the condition vector
(condition <- factor(c(rep("exp", 3), rep("temoin", 3))))

# ------------- Construct DESeq object

library(DESeq2)

(subreadData <- data.frame(row.names=colnames(subreadCounts), condition))
dataSet <- DESeqDataSetFromMatrix(countData = subreadCounts, colData = subreadData, design = ~ condition)

```

```{r}
count_data <- read.table("matriceuh.txt", header = TRUE, sep = '\t')

count_data <- count_data[,c(2,6:(ncol(count_data)-6))]

#matrix(data=matrice)

count_matrix <- count_data[,-1]

rownames(count_matrix) <- count_data[,1]

print(count_matrix)

(condition <- factor(c(rep("temoin", 3), rep("exp", 3))))
count_matrix <- as.matrix(count_matrix)

count_matrix[is.na(count_matrix)] <- 0
any(is.na(count_matrix))
library(DESeq2)

(subreadData <- data.frame(row.names=colnames(count_matrix), condition))
dataSet <- DESeqDataSetFromMatrix(countData = count_matrix, colData = subreadData, design = ~ condition)
```


```{r}
# analyse d'expression différentielle sur notre dds

dataSet <- DESeq(dataSet)
```

```{r}
# formatage des résultats sous forme de DataFrame

resultats <- results(dataSet)

rld <- rlogTransformation(dataSet)

resultats$padj <- p.adjust(resultat$pvalue, method = "BH")

de_genes <- subset(resultats, padj < 0.05)
```

```{r}
# exportation des résultats sous forme de MA-plot

plotMA(resultats, ylim = c(-6,6))
plotPCA(rld, intgroup="condition")

library("EnhancedVolcano")

EnhancedVolcano(resultats,lab = rownames(resultats), x = 'log2FoldChange', y = 'pvalue')
```