# We can install Bowtie through conda. We use the light version micromamba for this.
FROM mambaorg/micromamba:1.5.0-alpine

# Install Bowtie through Bioconda channel
RUN micromamba install -y -n base -c bioconda bowtie